name: VoterSystem
main: com.ericlam.mc.votesystem.main.VoterSystemSpigot
version: 1.5.8-SNAPSHOT
author: Hydranapse_
depend: [HyperNiteMC-Core]
softdepend: [PlaceholderAPI]
description: Server Voting Plugin